### ISSUE TITLE
Using trait alias feature instead of auto macro

### ISSUE THREAD

**Issue by adamAndMath** [anvil777/maths-traits#1]
If I understand your auto macro correctly, you have essentially reimplemented the trait alias feature. As this library already utilizes several unstable features, I suggest replacing all uses of the auto macro with trait aliases.
This would turn all auto macros into shorthands for their requirements. Thus make the type-checker complain about the specific base traits that are missing instead of stating that the specific group isn't implemented.
This may very well not be desired, as the context is lost, but it makes it more clear what is actually wrong.

**Comment by adamAndMath** [comment]
This is currently not possible do to [Trait alias makes method call ambigous](https://github.com/rust-lang/rust/issues/60021).
I could move the conflicting traits and impls into separate folders to work around this.

**Comment by jsmith628** [comment]
Back when I implemented the macro, trait aliases hadn't been added. In fact, I tried to see if they were a feature I could use and was pretty surprised when they weren't. However, it seems I wasn't paying attention and they were added in the time since I did that.

Now, on the topic of the compiler output, the error messages it currently gives already are _effectively_ as you say as it's smart enough to figure out and say that the "alias" isn't implemented because of one of the feature traits. Of course, it does _mention_ the alias, but it's such a small part of the message that it's not really worth using an alternate implementation of a base language feature for it.

In any case, I went ahead and pulled your changes into the testing branch. I'm going to leave them there for now until more features and/or documentation is added since it doesn't really change the system at all and potentially to wait for that [issue](https://github.com/rust-lang/rust/issues/60021) gets fixed.
